### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DanTremonti** [DanTremonti/smart-surveillance#1]
v0.1
- [x] Prepare paper in IEEE format
- [x] Add a surveillance footage
- [ ]  Add a script to handle threat (email and sms) and call it from main.py
- - [ ] Send email
- - [ ] Send SMS
- - [x] Script needs access the stored data from config file
- - [ ] We'll need to add a minimum time interval between alerts being sent through email/sms
- [x] Modify README
- [x] Load the application onto raspberry pi module
- [x] Collect evaluation results

v0.2
- [ ] Config file encryption (protect user's mail password)
- - [ ] Necessary to switch to yaml format?
- [ ] An image can have multiple threat objects in it. We'll have to properly segregate them to send as an alert msg
- - [x] Add different box colors
- - [ ] Add overlapping boxes to increase threat level
- [ ] Retrain the model with necessary classes only (a person wearing mask, having gun, etc,.)

Note: Update `requirements.txt` before merging with raspi-testing branch

**Comment by DanTremonti** [comment]
https://github.com/DanTremonti/smart-surveillance/issues/1#issue-1167192162
Need to work on email alert. I'm getting authentication error. Kindly pull, update config with your credentials and check. @raju-9-11
